# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PAGHed0FrZUVOZf5bVMTqCN7wWSpWlb8
"""

# upload csv file before testing
import pandas as pd
file_name = "weather.csv"
df = pd.read_csv(file_name)

#Q. 1)  Find all the unique 'Wind Speed' values in the data.
unique_wind_speed = df['Wind Speed_km/h'].unique()
print (unique_wind_speed)

# Q. 2) Find the number of times when the 'Weather is exactly Clear'.
clear_weather = [(weather, temp) for weather, temp in zip(df['Weather'], df['Temp_C']) if weather == "Clear"]
print(len(clear_weather))

# Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.
wind_speed = df[df['Wind Speed_km/h'] == 4]
print(len(wind_speed))

# Q. 4) Find out all the Null Values in the data.
print(df.isnull().sum())

# Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.
df.rename(columns={'Weather':'Weather Conditions'}, inplace = True)
print(df['Weather Conditions'])

# Q. 6) What is the mean 'Visibility' ?
print(df['Visibility_km'].mean())

# Q. 7) What is the Standard Deviation of 'Pressure'  in this data?
print(df['Press_kPa'].std())

# Q. 8) What is the Variance of 'Relative Humidity' in this data ?
print(df['Rel Hum_%'].var())

# Q. 9) Find all instances when 'Snow' was recorded.
print(df[df['Weather Conditions']=='Snow'])

# Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.
print(df[(df['Wind Speed_km/h'] > 24) & (df['Visibility_km'] == 25)])

# Q. 11) What is the Mean value of each column against each 'Weather Condition ?
weathers = df['Weather Conditions'].unique()
for i in weathers:
  print(i)
  print(df.mean())
  print('\n\n')

# Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?
for i in weathers:
  print(i)
  print('min:\n')
  print(df.min())
  print('\nmax:')
  print(df.max())
  print('\n\n')

# Q. 13) Show all the Records where Weather Condition is Fog.
print(df[df['Weather Conditions']=='Fog'])

# Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.
print(df[(df['Weather Conditions'] == 'Clear') | (df['Visibility_km'] > 40)])

# Q. 15) Find all instances when :
# A. 'Weather is Clear' and 'Relative Humidity is greater than 50'
# or
# B. 'Visibility is above 40'

print(df[((df['Weather Conditions'] == 'Clear') & (df['Rel Hum_%']>50)) | (df['Visibility_km']>40)])
